# [START cloudbuild_python_yaml]
# [START cloudbuild_python_dependencies_yaml]
steps:
  # Install dependencies
  - id: "copy env"
    name: gcr.io/cloud-builders/git
    args:
      - "-c"
      - |
        echo "$$ENV_FILE" >> .env
        chmod 400 .env
    entrypoint: bash
    secretEnv:
      - ENV_FILE

  - id: "install deps"
    name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  # [END cloudbuild_python_dependencies_yaml]

  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]
  # [END cloudbuild_python_image_yaml]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "run deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "--port",
        "${_PORT}",
        "--allow-unauthenticated", # might have to be removed?
      ]

substitutions:
  _REGION: us-west1
  _SERVICE_NAME: greenflags-backend
  _SECRET_NAME: backend_env
  _PORT: "8080"

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/${_SECRET_NAME}/versions/latest
      env: ENV_FILE
